#%RAML 1.0 Library

types:
  GetWeatherResponse: !include GetWeatherResponse.raml
  GetCitiesByCountryResponse: !include GetCitiesByCountryResponse.raml
  ErrorResponse: !include ErrorResponse.raml
  
  