#%RAML 1.0 NamedExample
NewDataSet:
  Location: "Melbourne"
  Time: "11 AM"
  Wind: "15 km per hr"
  Visibility: "10 km"
  SkyConditions: "sunny"
  Temperature: 18
  DewPoint: "2 C"
  RelativeHumidity: 35
  Status: "Normal"